import { PlatformConfig, PlatformId } from '../types';

export const PLATFORMS: Record<PlatformId, PlatformConfig> = {
  radreel: {
    id: 'radreel',
    name: 'RadReel',
    color: 'hsl(0 84% 60%)',
    colorClass: 'bg-platform-radreel',
    api: {
      baseUrl: 'https://dramabos.asia/api/radreel/api/v1',
      health: '/health',
      home: '/home?lang=id&tab=17',
      search: '/search?lang=id',
      rank: '/rank?type=1&lang=id',
      drama: '/drama',
      episodes: '/episodes',
      play: '/play',
      recommend: '/recommend',
    },
    lang: 'id',
    menu: ['home', 'search', 'rank', 'bookmark'],
  },
  flickreels: {
    id: 'flickreels',
    name: 'FlickReels',
    color: 'hsl(217 91% 60%)',
    colorClass: 'bg-platform-flickreels',
    api: {
      baseUrl: 'https://dramabos.asia/api/flick',
      health: '/health',
      home: '/home?lang=6',
      latest: '/latest?lang=6',
      search: '/search?lang=6',
      exchange: '/exchange?lang=6',
      trending: '/trending?lang=6',
      drama: '/drama',
    },
    lang: 6,
    menu: ['home', 'latest', 'search', 'trending'],
  },
  dotdrama: {
    id: 'dotdrama',
    name: 'DotDrama',
    color: 'hsl(271 81% 56%)',
    colorClass: 'bg-platform-dotdrama',
    api: {
      baseUrl: 'https://dramabos.asia/api/dotdrama',
      health: '/health',
      home: '/home',
      search: '/search',
      categories: '/categories',
      collections: '/collections',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['home', 'search', 'categories', 'collections'],
  },
  netshort: {
    id: 'netshort',
    name: 'NetShort',
    color: 'hsl(142 71% 45%)',
    colorClass: 'bg-platform-netshort',
    api: {
      baseUrl: 'https://dramabos.asia/api/netshort',
      health: '/health',
      discover: '/discover',
      search: '/search',
      categories: '/categories',
      meta: '/meta',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['discover', 'search', 'categories', 'meta'],
  },
  shortmax: {
    id: 'shortmax',
    name: 'ShortMax',
    color: 'hsl(45 93% 47%)',
    colorClass: 'bg-platform-shortmax',
    api: {
      baseUrl: 'https://dramabos.asia/api/shortmax',
      health: '/health',
      home: '/home',
      search: '/search',
      episodes: '/episodes',
      batch: '/batch',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['home', 'search', 'episodes', 'batch'],
  },
  starshort: {
    id: 'starshort',
    name: 'StarShort',
    color: 'hsl(330 81% 60%)',
    colorClass: 'bg-platform-starshort',
    api: {
      baseUrl: 'https://dramabos.asia/api/starshort',
      health: '/health',
      home: '/home',
      search: '/search',
      rank: '/rank',
      unlock: '/unlock',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['home', 'search', 'rank', 'unlock'],
  },
  stardusttv: {
    id: 'stardusttv',
    name: 'StardustTV',
    color: 'hsl(239 84% 67%)',
    colorClass: 'bg-platform-stardusttv',
    api: {
      baseUrl: 'https://dramabos.asia/api/stardusttv',
      health: '/health',
      home: '/home',
      search: '/search',
      episodes: '/episodes',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['home', 'search', 'episodes'],
  },
  dramadash: {
    id: 'dramadash',
    name: 'DramaDash',
    color: 'hsl(173 80% 40%)',
    colorClass: 'bg-platform-dramadash',
    api: {
      baseUrl: 'https://dramabos.asia/api/dramadash',
      health: '/health',
      home: '/home',
      tabs: '/tabs',
      search: '/search',
      episode: '/episode',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['home', 'tabs', 'search', 'episode'],
  },
  dramawave: {
    id: 'dramawave',
    name: 'DramaWave',
    color: 'hsl(187 92% 50%)',
    colorClass: 'bg-platform-dramawave',
    api: {
      baseUrl: 'https://dramabos.asia/api/dramawave',
      health: '/health',
      home: '/home',
      search: '/search',
      feed: '/feed',
      play: '/play',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['home', 'search', 'feed', 'play'],
  },
  dramabox: {
    id: 'dramabox',
    name: 'DramaBox',
    color: 'hsl(25 95% 53%)',
    colorClass: 'bg-platform-dramabox',
    api: {
      baseUrl: 'https://dramabos.asia/api/dramabox',
      health: '/health',
      foryou: '/foryou',
      search: '/search',
      rank: '/rank',
      classify: '/classify',
      watch: '/watch',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['foryou', 'search', 'rank', 'classify', 'watch'],
  },
  viglo: {
    id: 'viglo',
    name: 'Viglo',
    color: 'hsl(84 81% 44%)',
    colorClass: 'bg-platform-viglo',
    api: {
      baseUrl: 'https://dramabos.asia/api/viglo',
      health: '/health',
      home: '/home',
      search: '/search',
      rank: '/rank',
      program: '/program',
      play: '/play',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['home', 'search', 'rank', 'program', 'play'],
  },
  micro: {
    id: 'micro',
    name: 'Micro',
    color: 'hsl(220 9% 46%)',
    colorClass: 'bg-platform-micro',
    api: {
      baseUrl: 'https://dramabos.asia/api/micro',
      health: '/health',
      list: '/list',
      search: '/search',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['list', 'search', 'drama'],
  },
  melolo: {
    id: 'melolo',
    name: 'Melolo',
    color: 'hsl(347 77% 50%)',
    colorClass: 'bg-platform-melolo',
    api: {
      baseUrl: 'https://dramabos.asia/api/melolo',
      health: '/health',
      home: '/home',
      search: '/search',
      detail: '/detail',
      video: '/video',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['home', 'search', 'detail', 'video'],
  },
  meloshort: {
    id: 'meloshort',
    name: 'MeloShort',
    color: 'hsl(263 70% 50%)',
    colorClass: 'bg-platform-meloshort',
    api: {
      baseUrl: 'https://dramabos.asia/api/meloshort',
      health: '/health',
      home: '/home',
      ranking: '/ranking',
      recommend: '/recommend',
      search: '/search',
      play: '/play',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['home', 'ranking', 'recommend', 'search', 'play'],
  },
  reelife: {
    id: 'reelife',
    name: 'Reelife',
    color: 'hsl(160 84% 39%)',
    colorClass: 'bg-platform-reelife',
    api: {
      baseUrl: 'https://dramabos.asia/api/reelife',
      health: '/health',
      init: '/init',
      home: '/home',
      browse: '/browse',
      search: '/search',
      book: '/book',
      play: '/play',
      drama: '/drama',
    },
    lang: 'id',
    menu: ['init', 'home', 'browse', 'search', 'book', 'play'],
  },
};

export const PLATFORM_LIST = Object.values(PLATFORMS);

export const getPlatformById = (id: PlatformId): PlatformConfig => {
  return PLATFORMS[id] || PLATFORMS.radreel;
};
